# Generated by Django 5.2 on 2025-10-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_category_options_rename_title_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='title',
        ),
    ]
