# Generated by Django 5.2 on 2025-10-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_name_work_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='title',
            new_name='work_title',
        ),
    ]
