# Generated by Django 5.2 on 2025-11-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_title_work_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
