# Generated by Django 5.2 on 2025-11-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_work_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
