# Generated by Django 5.2 on 2025-11-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_work_is_featured_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='worker',
        ),
        migrations.AddField(
            model_name='payment',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.work'),
        ),
    ]
