# Generated by Django 5.2 on 2025-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_payment_worker_payment_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_count',
            field=models.FloatField(default=0),
        ),
    ]
