# Generated by Django 5.2 on 2025-10-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattexts',
            name='chatbox',
        ),
        migrations.RemoveField(
            model_name='chattexts',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatBox',
        ),
        migrations.DeleteModel(
            name='ChatTexts',
        ),
    ]
