# Generated by Django 5.2 on 2025-10-26 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
        ('service', '0004_rename_title_work_work_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBox',
            new_name='Conversation',
        ),
        migrations.RenameModel(
            old_name='ChatTexts',
            new_name='ConversationMessages',
        ),
    ]
