# Generated by Django 5.2 on 2025-10-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_rename_chatbox_conversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessages',
            old_name='chatbox',
            new_name='conversation',
        ),
    ]
